export const TestimonialsData = [
    {
        studentPic: "https://randomuser.me/api/portraits/men/32.jpg",
        picAlt: "Review by John Doe",
        quote: "This course has been a game-changer for my career. The hands-on projects were incredibly helpful!",
        studentName: "John Doe",
        roleFR: "Software Engineer",
    },
    {
        studentPic: "https://randomuser.me/api/portraits/women/44.jpg",
        picAlt: "Review by Jane Smith",
        quote: "Absolutely loved the learning environment and the supportive community. Highly recommend!",
        studentName: "Jane Smith",
        roleFR: "Data Analyst",
    },
    {
        studentPic: "https://randomuser.me/api/portraits/men/46.jpg",
        picAlt: "Review by Bob Brown",
        quote: "The instructors are very knowledgeable and approachable. I've gained a lot of practical skills.",
        studentName: "Bob Brown",
        roleFR: "Project Manager",
    },
    {
        studentPic: "https://randomuser.me/api/portraits/women/50.jpg",
        picAlt: "Review by Alice Johnson",
        quote: "Joining this program was one of the best decisions of my life. The curriculum is very thorough.",
        studentName: "Alice Johnson",
        roleFR: "UX Designer",
    },
    {
        studentPic: "https://randomuser.me/api/portraits/men/64.jpg",
        picAlt: "Review by Carlos Esteban",
        quote: "Great balance between theory and practical application. The support staff was always available and helpful.",
        studentName: "Carlos Esteban",
        roleFR: "Marketing Manager",
    },
    {
        studentPic: "https://randomuser.me/api/portraits/men/70.jpg",
        picAlt: "Review by David Lee",
        quote: "The course content is very relevant and the projects are challenging. I feel much more confident now.",
        studentName: "David Lee",
        roleFR: "Product Manager",
    },
    {
        studentPic: "https://randomuser.me/api/portraits/women/72.jpg",
        picAlt: "Review by Emily White",
        quote: "The instructors are very knowledgeable and approachable. I've gained a lot of practical skills.",
        studentName: "Emily White",
        roleFR: "Software Engineer",
    },
];
